language: node_js
node_js:
  - "6"
cache:
  directories:
    - node_modules
install: npm install
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - ENCRYPTED_TOKEN:
      secure: "HXmAB3bF5utX8OD2hrm5Af+Bm8GGaZxwqouLzIL5ZAYZN7SxnNpShU4x05GPSRKO4Q/x2rAvfpYWIJn7Ual503+FOgo2WSq1srsNh4rGKNTz0OncXwLn0ksFpT+5WMQ+N/IbayzwG8C3FJO24kRXIl2rdL7bIzCzS2jgkcMSVZRmKJNi8RxMviRiuPVjxIA46q4KZ7/CG94scYdHcMTXh6GkaKzOLUEWMDFEvFVpRwKv0mcMMTuwv/IsG0oA+CrWliuriYuc+78Ox4FI8NZImvC1hLbe36LL9ltpv1bYC0kXWSQnHeb9A36ay4TxjSyiX9zSudyXlUEul+C4Sp0GTRef12K4vnoQ/PaYVPOPMjcnVZVg101VdgRdrDjiGvC9NpsP54thL020PWmpyXtacRTInQz2ibK1ptA3OWEbVemQZYuLcp08RysQyzKMnY2kvv26baJEu4BigvN1VQU4Ufi9MGNHKc+VMTA//YDGIyDd3cULAk0s5nmlwYIzD7NtS7JWsJnMVN82IJaj7CXqLBCycAiP9b0z9G+JDEjbEvr4sdP6U+XeicXZR+GkVhsRMgGDGN5GbPnZBUByB9/Aq9sqRVaoMLgG+lWs+nbFtoiczcvHs1b51oGVUzTFg5czbGV2oRkWj8O6NEPScN87scKr+H2VZTZbSNfyTBP1ckU="
    - COMMIT_AUTHOR_EMAIL: "dsevilla192@icloud.com"
dist: trusty
sudo: false
